### PR TITLE
Changed font for profile's key for better readability.

### PR DESCRIPTION
**Pull request by murderered**
Now it's the already included Monospaced font. It was hard to differentiate between 0 and O (depending on device).

### CODE REVIEW

**Comment by gustavomondron** [comment]
Could you make a new pull request including only the changes in AddProfileActivity.java and EditProfileActivity.java? Than you very much for your help!

**Comment by murderered** [comment]
Okay, you can use this patch:

https://dl.dropboxusercontent.com/u/15921527/0001-Changed-font-of-profile-s-private-key-for-better-rea.patch

**Comment by murderered** [comment]
Okay, i merged my fork with your current master. Now it should be easy to pull the changes.

**Comment by gustavomondron** [comment]
Your request has been included to Twik 1.3.1, which is rolling out starting now in the Play Store for beta testers.

To get beta updates, you can join our Google+ community and follow the instructions.

https://plus.google.com/u/0/communities/111229668892776713870

Thank you very much for your help.

**Pull request closed without merging**
